### PR TITLE
Add KB2040

### PR DESCRIPTION
**Pull request by caternuson**
Adds support for the KB2040

### CODE REVIEW

**Comment by BlitzCityDIY** [comment]
hihi @caternuson - thanks for adding! tested with the KB2040. i updated the u2if.py file to include the PID/VID for the KB2040 and was able to build and test locally. ran neopixel, i2c and gpio tests. also updated the README's and the build-all script

**Comment by caternuson** [comment]
@BlitzCityDIY thanks. curious if you found this step to actually be necessary?

> i updated the u2if.py file to include the PID/VID for the KB2040 and was able to build and test locally.

i *think* that's unrelated to the firmware itself

**Comment by BlitzCityDIY** [comment]
@caternuson i am honestly not sure. i was having some build errors at first so i was comparing to previous PRs but the error ended up being a line ending issue on the .pio files since i use WSL

**Comment by caternuson** [comment]
OK, hopefully it was just the line ending. The older PR's touched other files to try and update the entire repo, which includes more than just the firmware. This one was focuses on just the firmware.

Thanks for updating the readme's and build script.

**Pull request merged**
