### PR TITLE
Adding EPD Feather

### PR DESCRIPTION
**Pull request by BlitzCityDIY**
Adding EPD Feather support. PR that @ladyada has been testing

### CODE REVIEW

**Comment by caternuson** [comment]
I don't have hardware to test. Generally looks OK, with the nominal fixes for SPI0/SPI1 that @ladyada discovered when testing with actual hardware.

**Comment by ladyada** [comment]
i tested this UF2 as long as its the one with the crystal-startup-delay thingy!

**Comment by BlitzCityDIY** [comment]
yes, i did add that to my local install of the pico sdk that is pinned. @caternuson that's where that is defined right?

**Comment by caternuson** [comment]
The "crystal-startup-delay thingy" would be this:
```
Local copy of pico-sdk had changes to pico-sdk/src/rp2_common/hardware_xosc/xosc.c:

    xosc_hw->startup = startup_delay * 64;
```
from here:
https://github.com/adafruit/u2if/pull/1

In this repo's current state, this is still a **required manual step**. That is due to the commit point referenced by the pico-sdk submodule (`pico-sdk @ fc10a97`). It pre-dates this PR:
https://github.com/raspberrypi/pico-sdk/pull/457
which adds a way to configure this without modifying SDK source code. That PR thread also mentions the reason for needing this extra delay.

Suggest making a new issue/PR to address updating the pico-sdk submodule and dealing with startup delay.

**Review by caternuson — APPROVED** [review]

**Pull request merged**
